from __future__ import annotations

from collections.abc import Sequence
from typing import Iterator, NewType, Protocol

PageId = NewType("PageId", int)
SlotId = NewType("SlotId", int)
RowId = tuple[PageId, SlotId]


class Storage(Protocol):
    def create_table(self, name: str, columns: Sequence[str]) -> None: ...
    def table_exists(self, name: str) -> bool: ...
    def get_columns(self, name: str) -> Sequence[str]: ...
    def insert_row(self, table: str, row: tuple[str, ...]) -> None: ...
    def scan_rows(self, table: str) -> Iterator[tuple[RowId, tuple[str, ...]]]: ...
    # NOTE: A RowId may be invalidated by a growth update (new row larger
    # than the old slot). Re-scan the table after commit to get fresh RowIds
    # before issuing a subsequent mark_update or mark_delete.
    def mark_update(self, table: str, row_id: RowId, new_row: tuple[str, ...]) -> None: ...
    def mark_delete(self, table: str, row_id: RowId) -> None: ...
    def commit(self) -> None: ...
    def vacuum(self) -> None: ...
    def close(self) -> None: ...
